@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-dark">{{ __("New Item") }}</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
								<li class="breadcrumb-item"><a href="{{ route("items.employee.index") }}">{{ __("Item") }}</a></li>
								<li class="breadcrumb-item active">{{ __("New Item") }}</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
							<div class="table-responsive">
								<div class="card">
									<div class="card-body">
										<form method="POST" action="{{ route('items.employee.store') }}" enctype="multipart/form-data">

											<div class="row">
												<div class="col-12 mb-3">
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Store Information") }}</div>
														</div>
														<div class="card-body">
															<div class="form-group row">
																<label for="store_id" class="col-2 col-form-label">Store Name <span style="color: red">*</span></label>
																<div class="col-10">
																	<select class="form-control" name="store_id">
																		@foreach ($stores as $store)
																		<option value="{{ $store->id }}">{{ $store->name }} ({{ $store->code }})</option>
																		@endforeach
																	</select>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
					
											<div class="row">
												<div class="col-12 mb-3">
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Item Information") }}</div>
														</div>
														<div class="card-body">
															<div class="form-group row">
																@csrf
																<label for="item_no" class="col-3 col-form-label">Item No <span style="color: red">*</span></label>
																<div class="col-9">
																	<!-- <input type="text" class="form-control" name="item_no" required /> -->
																	<label class="col-form-label"><span style="color: lightgrey"><i>auto generated by system.</i></span></label>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_name" class="col-3 col-form-label">Item Name <span style="color: red">*</span></label>
																<div class="col-9">
																	<input type="text" class="form-control" name="item_name" required value="{{ old('item_name') }}" />
																</div>
															</div>
															<div class="form-group row">
																<label for="item_weight" class="col-3 col-form-label">Item Weight <span style="color: red">*</span></label>
																<div class="col-9">
																	<div class="input-group">
																		{{-- <input type="number" step="any" min="0" class="form-control" name="item_weight" required value="{{ old('item_weight') }}" placeholder="Ex: 50.45" /> --}}
																		<input type="text" class="form-control" name="item_weight" required value="{{ old('item_weight') }}" placeholder="Ex: 50.45" />
																		<div class="input-group-append">
																			<div class="input-group-text">gr</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="category_id" class="col-3 col-form-label">Category <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="category_id" id="category_id">
																		@foreach ($categories as $category)
																			<option value="{{ $category->id }}">{{ $category->description }} ({{ $category->code }})</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_gold_rate" class="col-3 col-form-label">Gold Rate <span style="color: red">*</span></label>
																<div class="col-9">
																	<div class="input-group">
																		{{-- <input type="number" step="0.1" min="0" class="form-control" name="item_gold_rate" id="item_gold_rate" required value="{{ old('item_gold_rate') }}" placeholder="Ex: 37.5"/> --}}
																		<input type="text" class="form-control" name="item_gold_rate" id="item_gold_rate" required value="{{ old('item_gold_rate') }}" placeholder="Ex: 37.5"/>
																		<div class="input-group-append">
																			<div class="input-group-text">%</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="allocation_id" class="col-3 col-form-label">Allocation <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="allocation_id">
																		@foreach ($allocations as $allocation)
																			<option value="{{ $allocation->id }}">{{ $allocation->description }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_status_id" class="col-3 col-form-label">Item Status <span style="color: red">*</span></label>
																<div class="col-9">
																	<!-- <select class="form-control" name="item_status_id" readonly> -->
																		@foreach ($itemstatuses as $itemstatus)
																			@if ($itemstatus->code == 'new')
																				<input type="text" class="form-control" name="item_status_id" readonly hidden value="{{ $itemstatus->id }}" />
																				<input type="text" class="form-control" name="item_status" readonly value="{{ $itemstatus->description }}" />
																				@break
																			@endif
																			<!-- <option value="{{ $itemstatus->id }}" {{ $itemstatus->code == 'new' ? 'selected' : '' }}>{{ $itemstatus->description }}</option> -->
																		@endforeach
																	<!-- </select> -->
																</div>
															</div>
															<div class="form-group row">
																<label for="inventory_status_id" class="col-3 col-form-label">Inv Status <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="inventory_status_id">
																		@foreach ($inventorystatuses as $inventorystatus)
																			<option value="{{ $inventorystatus->id }}">{{ $inventorystatus->description }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="created_by" class="col-3 col-form-label">Created By</label>
																<div class="col-9">
																	<select class="form-control" name="created_by" readonly>
																		{{-- <option></option> --}}
																		@foreach ($users as $user)
																			<option value="{{ $user->id }}">{{ $user->name }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="created_by" class="col-3 col-form-label">Photos</label>
																<div class="col-9">
																	<input type="file" id="photos" name="images[]" multiple style="display:none;">
																	<button class="add-photos btn btn-light">Add Photos</button>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
					
											<div class="float-right">
												<a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
												<button type="submit" class="btn btn-primary" name="action" value="save">{{ __("Save") }}</button>
												<button type="submit" class="btn btn-primary" name="action" value="save entry sales">{{ __("Save & Entry Sales") }}</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

        </div>
    </div>
</div>
@endsection

@section('custom-script')
<script type="text/javascript">
	// $(function() {
    //     $('#sales_at').datepicker();
    // });

	$('.add-photos').on('click', function() { $('#photos').click();return false;});

    document.getElementById("item_gold_rate").value = 37.5;
	$('#category_id').on('change', function(e) {
		var categoryText = (this.options[this.selectedIndex].text).toLowerCase();
		if(categoryText == "kalung (k)") {
			document.getElementById("item_gold_rate").value = 42.0;
		} else {
			document.getElementById("item_gold_rate").value = 37.5;
		}
	});
</script>
@endsection