@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-dark">{{ __("New Item Book") }}</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="/">{{ __("Home") }}</a></li>
								<li class="breadcrumb-item"><a href="{{ route("items.index") }}">{{ __("Item Book") }}</a></li>
								<li class="breadcrumb-item active">{{ __("New Item Book") }}</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
							<div class="table-responsive">
								<div class="card">
									<div class="card-body">
										<form method="POST" action="{{ route('items.store') }}" enctype="multipart/form-data">

											<div class="row">
												<div class="col-12 mb-3">
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Store Information") }}</div>
														</div>
														<div class="card-body">
															<div class="form-group row">
																<label for="store_id" class="col-2 col-form-label">Store Name <span style="color: red">*</span></label>
																<div class="col-10">
																	<select class="form-control" name="store_id">
																		@foreach ($stores as $store)
																		<option value="{{ $store->id }}">{{ $store->name }} ({{ $store->code }})</option>
																		@endforeach
																	</select>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
					
											<div class="row">
												<div class="col-6 mb-3">
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Item Information") }}</div>
														</div>
														<div class="card-body">
															<div class="form-group row">
																@csrf
																<label for="item_no" class="col-3 col-form-label">Item No <span style="color: red">*</span></label>
																<div class="col-9">
																	<!-- <input type="text" class="form-control" name="item_no" required /> -->
																	<label class="col-form-label"><span style="color: lightgrey"><i>auto generated by system.</i></span></label>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_name" class="col-3 col-form-label">Item Name <span style="color: red">*</span></label>
																<div class="col-9">
																	<input type="text" class="form-control" name="item_name" required value="{{ old('item_name') }}" />
																</div>
															</div>
															<div class="form-group row">
																<label for="item_weight" class="col-3 col-form-label">Item Weight <span style="color: red">*</span></label>
																<div class="col-9">
																	<div class="input-group">
																		{{-- <input type="number" step="any" min="0" class="form-control" name="item_weight" required value="{{ old('item_weight') }}" placeholder="Ex: 50.45" /> --}}
																		<input type="text" class="form-control" name="item_weight" required value="{{ old('item_weight') }}" placeholder="Ex: 50.45" />
																		<div class="input-group-append">
																			<div class="input-group-text">gr</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="category_id" class="col-3 col-form-label">Category <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="category_id" id="category_id">
																		@foreach ($categories as $category)
																			<option value="{{ $category->id }}">{{ $category->description }} ({{ $category->code }})</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_gold_rate" class="col-3 col-form-label">Gold Rate <span style="color: red">*</span></label>
																<div class="col-9">
																	<div class="input-group">
																		{{-- <input type="number" step="0.1" min="0" class="form-control" name="item_gold_rate" id="item_gold_rate" required value="{{ old('item_gold_rate') }}" placeholder="Ex: 37.5"/> --}}
																		<input type="text" class="form-control" name="item_gold_rate" id="item_gold_rate" required value="{{ old('item_gold_rate') }}" placeholder="Ex: 37.5"/>
																		<div class="input-group-append">
																			<div class="input-group-text">%</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="allocation_id" class="col-3 col-form-label">Allocation <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="allocation_id">
																		@foreach ($allocations as $allocation)
																			<option value="{{ $allocation->id }}">{{ $allocation->description }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="item_status_id" class="col-3 col-form-label">Item Status <span style="color: red">*</span></label>
																<div class="col-9">
																	<!-- <select class="form-control" name="item_status_id" readonly> -->
																		@foreach ($itemstatuses as $itemstatus)
																			@if ($itemstatus->code == 'new')
																				<input type="text" class="form-control" name="item_status_id" readonly hidden value="{{ $itemstatus->id }}" />
																				<input type="text" class="form-control" name="item_status" readonly value="{{ $itemstatus->description }}" />
																				@break
																			@endif
																			<!-- <option value="{{ $itemstatus->id }}" {{ $itemstatus->code == 'new' ? 'selected' : '' }}>{{ $itemstatus->description }}</option> -->
																		@endforeach
																	<!-- </select> -->
																</div>
															</div>
															<div class="form-group row">
																<label for="inventory_status_id" class="col-3 col-form-label">Inv Status <span style="color: red">*</span></label>
																<div class="col-9">
																	<select class="form-control" name="inventory_status_id">
																		@foreach ($inventorystatuses as $inventorystatus)
																			<option value="{{ $inventorystatus->id }}">{{ $inventorystatus->description }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="created_by" class="col-3 col-form-label">Created By</label>
																<div class="col-9">
																	<select class="form-control" name="created_by">
																		{{-- <option></option> --}}
																		@foreach ($users as $user)
																			<option value="{{ $user->id }}">{{ $user->name }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
														</div>
													</div>
												</div>
												<div class="col-6 mb-3">
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Sales Information") }}</div>
														</div>
														<div class="card-body">
															<div class="form-group row">
																<label for="sales_status_id" class="col-3 col-form-label">Sales Status</label>
																<div class="col-9">
																	<select class="form-control" name="sales_status_id">
																		<option selected></option>
																		@foreach ($salesstatuses as $salesstatus)
																			<option value="{{ $salesstatus->id }}">{{ $salesstatus->code }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
															<div class="form-group row">
																<label for="sales_price" class="col-3 col-form-label">Sales Price</label>
																<div class="col-9">
																	<div class="input-group">
																		<div class="input-group-prepend">
																				<div class="input-group-text">Rp</div>
																		</div>
																		<input type="number" step="any" min="0" class="form-control" name="sales_price" value="{{ old('sales_price') }}" />
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="sales_at" class="col-3 col-form-label">Sales At</label>
																<div class="col-9">
																	<div class="input-group">
																		<input type="text" class="form-control dateselect" id="sales_at" name="sales_at" placeholder="select date" />
																	</div>
																</div>
															</div>
															<div class="form-group row">
																<label for="sales_by" class="col-3 col-form-label">Sales By</label>
																<div class="col-9">
																	<select class="form-control" name="sales_by">
																		<option></option>
																		@foreach ($users as $user)
																			<option value="{{ $user->id }}">{{ $user->name }}</option>
																		@endforeach
																	</select>
																</div>
															</div>
														</div>
													</div>
													<div class="card">
														<div class="card-header">
															<div class="card-title">{{ __("Photos") }}</div>
															<label class="btn-sm btn-primary float-right">
																<span><i class="nav-icon fas fa-plus"></i></span> <input type="file" id="photos" name="images[]" multiple style="display:none;">
															</label>
															<div class="card-body">
																<div class="form-group row">
																	<div id="carouselPhotos" class="carousel slide" data-ride="carousel" style="display:none">
																		<div class="carousel-inner">
																			
																		</div>
																		<a class="carousel-control-prev" href="#carouselPhotos" role="button" data-slide="prev">
																			<span class="carousel-control-custom-icon" aria-hidden="true">
																				<i class="fas fa-chevron-left"></i>
																			</span>
																			<span class="sr-only">Previous</span>
																		</a>
																		<a class="carousel-control-next" href="#carouselPhotos" role="button" data-slide="next">
																			<span class="carousel-control-custom-icon" aria-hidden="true">
																				<i class="fas fa-chevron-right"></i>
																			</span>
																			<span class="sr-only">Next</span>
																		</a>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
					
											<div class="float-right">
												<a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">{{ __("Back") }}</a>
												<button type="submit" class="btn btn-primary">{{ __("Save") }}</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>

        </div>
    </div>
</div>
@endsection

@section('custom-script')
<script type="text/javascript">
	$(function() {
        $('#sales_at').datepicker();
    });

	$("#carouselPhotos").hide();

	document.getElementById('photos').addEventListener('change', readImage, false);

	document.getElementById("item_gold_rate").value = 37.5;
	$('#category_id').on('change', function(e) {
		var categoryText = (this.options[this.selectedIndex].text).toLowerCase();
		if(categoryText == "kalung (k)") {
			document.getElementById("item_gold_rate").value = 42.0;
		} else {
			document.getElementById("item_gold_rate").value = 37.5;
		}
	});

	function readImage() {
	   if (window.File && window.FileList && window.FileReader) {
	       var files = event.target.files; //FileList object
	       var output = $(".carousel-inner");
			$("#carouselPhotos").show();
			output.empty();
		
	       for (let i = 0; i < files.length; i++) {
	           var file = files[i];
	           if (!file.type.match('image')) continue;
	           
	           var picReader = new FileReader();
	           
	           picReader.addEventListener('load', function (event) {
	               var picFile = event.target;
					if (i == 0) {
						var html =  '<div class="carousel-item active">' + 
									'<img class="d-block w-100" src="'+picFile.result+'">' +
									'</div>'
					} else {
						var html =  '<div class="carousel-item">' + 
									'<img class="d-block w-100" src="'+picFile.result+'">' +
									'</div>'
					}
				
	               output.append(html);
	           });
			
	           picReader.readAsDataURL(file);
	       }
	   } else {
	       console.log('Browser not support');
	   }
	}
</script>
@endsection